### ISSUE TITLE
data object optimization

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/code-journal#16]
## reasoning
- adding sort methods and grabbers to the data model will help make code cleaner when having to access entries and entry content

## todo 
- [x] upon DOM creation, reference it as property of entry object
- [x] create method that gets object from id
- [x] create sort property containing methods that return based off of different parameters (date added, last modified, alphabetical)
- [x] ~~create method that gets DOM from id~~
(just call object from id method and use dot notation to access dom)
